### ISSUE TITLE
vm.max_map_count 65530 is too low

### ISSUE THREAD

**Issue by sknikolay** [Daabramov/Sonarqube-for-1c-docker#10]
Выполнение команд:
wsl --shutdown
wsl -d docker-desktop
sysctl -w vm.max_map_count=262144
sysctl -w fs.file-max=65536
решает проблему только на текущую сессию.
После перезагрузки компьютера то же сообщение об ошибке.
Как можно победить эту проблему?

**Comment by Daabramov** [comment]
Приветствую!

Проблема известная, так как данные настройки устанавливаются на время жизни.

Можно попробовать выполнить следующую команду
`echo "vm.max_map_count=262144" >> /etc/sysctl.conf`/

Такая настройка будет более перманентная. но есть риски, что при обновлении докер их образ может обновится, и эта настройка снестись.

**Comment by sknikolay** [comment]
> 
> 
> Приветствую!
> 
> Проблема известная, так как данные настройки устанавливаются на время жизни.
> 
> Можно попробовать выполнить следующую команду
> `echo "vm.max_map_count=262144" >> /etc/sysctl.conf`/
> 
> Такая настройка будет более перманентная. но есть риски, что при обновлении докер их образ может обновится, и эта настройка снестись.

Спасибо за оперативный ответ!
К сожалению данная команда не помогла.

**Comment by Daabramov** [comment]
> > Приветствую!
> > Проблема известная, так как данные настройки устанавливаются на время жизни.
> > Можно попробовать выполнить следующую команду
> > `echo "vm.max_map_count=262144" >> /etc/sysctl.conf`/
> > Такая настройка будет более перманентная. но есть риски, что при обновлении докер их образ может обновится, и эта настройка снестись.
> 
> Спасибо за оперативный ответ!
> К сожалению данная команда не помогла.

Попробуйте действия из поста https://github.com/docker/for-win/issues/5202#issuecomment-585504054

**Comment by Daabramov** [comment]
Или немного грязный хинт при старте системы https://github.com/docker/for-win/issues/5202#issuecomment-643045922

**Comment by sknikolay** [comment]
> 
> 
> > > Приветствую!
> > > Проблема известная, так как данные настройки устанавливаются на время жизни.
> > > Можно попробовать выполнить следующую команду
> > > `echo "vm.max_map_count=262144" >> /etc/sysctl.conf`/
> > > Такая настройка будет более перманентная. но есть риски, что при обновлении докер их образ может обновится, и эта настройка снестись.
> > 
> > 
> > Спасибо за оперативный ответ!
> > К сожалению данная команда не помогла.
> 
> Попробуйте действия из поста [docker/for-win#5202 (comment)](https://github.com/docker/for-win/issues/5202#issuecomment-585504054)

Этот вариант нерабочий. Даже при рестарте Docker Desktop не помогает.

**Comment by sknikolay** [comment]
> 
> 
> Или немного грязный хинт при старте системы [docker/for-win#5202 (comment)](https://github.com/docker/for-win/issues/5202#issuecomment-643045922)

Батник помог. Спасибо за помощь!
