### ISSUE TITLE
[Readme fix] max_map_count и docker desktop для windows

### ISSUE THREAD

**Issue by artesk** [Daabramov/Sonarqube-for-1c-docker#11]
На windows-хосте поймал баг, при котором изменения в sysctl.conf при перезагрузке сбрасывались.  Соответственно, каждый раз приходилось устанавливать   max_map_count. Нашел подтверждения, что я не один такой https://github.com/microsoft/WSL/issues/4232

Для себя решил таким финтом
```
В каталоге пользователя %userprofile% ( C:\Users\<username>) создать файл .wslconfig со следующим содержимым:
```

```
[wsl2]
kernelCommandLine = "sysctl.vm.max_map_count=262144"
```
После перезагрузки все будет хорошо. 

Не уверен, что \то общая проблема, но конкретно я время потратил. Возможно стоит указать в readme

**Comment by Daabramov** [comment]
Разместил в readme. Спасибо.

**Comment by Daabramov** [comment]
https://github.com/Daabramov/Sonarqube-for-1c-docker/commit/7fee8a3ec0ffd5d9b0a0971b995ab0443fd63f8c
