### ISSUE TITLE
Не запускается версия 9.4

### ISSUE THREAD

**Issue by kuzja086** [Daabramov/Sonarqube-for-1c-docker#12]
Падает с ошибкой:
`Caused by: org.apache.lucene.index.CorruptIndexException: checksum failed (hardware problem?) : expected=590a5c08 actual=9191dc5 (resource=BufferedChecksumIndexInput(NIOFSIndexInput(path=">`
Помогла только пересборка образа сонара  https://github.com/SonarSource/docker-sonarqube/tree/master/9/community с версией alpine 3.14.3
согласно https://github.com/SonarSource/docker-sonarqube/issues/544#issuecomment-1092517489

**Comment by Daabramov** [comment]
Привет!
Можешь дать сценарий воспроизведения?
Я смог запустить как с образа из хаба, так и локального собранного из репозитория.

**Comment by Daabramov** [comment]
Проблему обнаружил, исправил в сборке образа
https://github.com/Daabramov/Sonarqube-for-1c-docker/commit/6e8085ff81e66b2452e301c9c9eaa1edf85c9503
