### ISSUE TITLE
Не хватает предустановленного плагина Git

### ISSUE THREAD

**Issue by artbear** [Daabramov/Sonarqube-for-1c-docker#8]
Если подключать сервер из образа в текущем состоянии, при первом же анализе гит-репозиториев будет вылетать предупреждение о том, что нет scm-провайдеров. и приходится ставить Гит-плагин через маркетплейс.

Предлагаю сразу в образ добавить подходящую версию из маркетплейса Сонара

**Comment by Daabramov** [comment]
@artbear Довольно странный момент, у меня с 0 вроде сразу git scm  ставится, проверю попозже

**Comment by Daabramov** [comment]
Говорят в 8.5 гит плагин перенесли в ядро, надо проверить

**Comment by artbear** [comment]
у нас стоит 8.3 сервер, по умолчанию гит-плагина не было.

**Comment by Daabramov** [comment]
В версии 8.5 гит плагин включен в ядро
Обновил образ и компоуз до 8.5
